Traceback (most recent call last):
  File "/home/mnurek/anaconda3/envs/pdz/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/mnurek/anaconda3/envs/pdz/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mnurek/anaconda3/envs/pdz/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/mnurek/anaconda3/envs/pdz/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/mnurek/anaconda3/envs/pdz/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/mnurek/anaconda3/envs/pdz/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/mnurek/anaconda3/envs/pdz/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/mnurek/anaconda3/envs/pdz/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from river.base import DriftDetector
from river.drift import ADWIN, DDM, EDDM, HDDM_A, HDDM_W, KSWIN, PageHinkley
from river.stream import iter_pandas


def detect_concept_drift_from_stream(
    series: pd.DataFrame,
    detector: DriftDetector,
) -> List[int]:
    stream_iter = iter_pandas(series)
    detected_points = []
    for idx, (data, _) in enumerate(stream_iter):
        try:
            detector.update(data["y"])
        except Exception as e:
            print(detector, "Exception: ", e)
            return None
        if detector.drift_detected:
            detected_points.append(idx)
    return detected_points


drift_detectors = {
    "ADWIN": ADWIN(),
    "DDM": DDM(),
    "EDDM": EDDM(),
    "HDDM_A": HDDM_A(),
    "HDDM_W": HDDM_W(),
    "KSWIN": KSWIN(),
    "PageHinkley": PageHinkley(),
}

mean_shift_detected_points = {
    detector_name: detect_concept_drift_from_stream(
        series=mean_shift_series, detector=detector
    )
    for detector_name, detector in drift_detectors.items()
}
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn [4], line 2[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mriver[39;00m[38;5;21;01m.[39;00m[38;5;21;01mbase[39;00m [38;5;28;01mimport[39;00m DriftDetector
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mriver[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdrift[39;00m [38;5;28;01mimport[39;00m ADWIN, DDM, EDDM, HDDM_A, HDDM_W, KSWIN, PageHinkley
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mriver[39;00m[38;5;21;01m.[39;00m[38;5;21;01mstream[39;00m [38;5;28;01mimport[39;00m iter_pandas
[1;32m      6[0m [38;5;28;01mdef[39;00m [38;5;21mdetect_concept_drift_from_stream[39m(
[1;32m      7[0m     series: pd[38;5;241m.[39mDataFrame,
[1;32m      8[0m     detector: DriftDetector,
[1;32m      9[0m ) [38;5;241m-[39m[38;5;241m>[39m List[[38;5;28mint[39m]:

[0;31mImportError[0m: cannot import name 'DDM' from 'river.drift' (/home/mnurek/anaconda3/envs/pdz/lib/python3.9/site-packages/river/drift/__init__.py)
ImportError: cannot import name 'DDM' from 'river.drift' (/home/mnurek/anaconda3/envs/pdz/lib/python3.9/site-packages/river/drift/__init__.py)

