Traceback (most recent call last):
  File "/home/mnurek/anaconda3/envs/pdz/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/mnurek/anaconda3/envs/pdz/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mnurek/anaconda3/envs/pdz/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/mnurek/anaconda3/envs/pdz/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/mnurek/anaconda3/envs/pdz/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/mnurek/anaconda3/envs/pdz/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/mnurek/anaconda3/envs/pdz/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/mnurek/anaconda3/envs/pdz/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from collections import Counter

import seaborn as sns

counter = Counter(df_y.values)
sns.barplot(y=list(counter.values()), x=list(counter.keys()), errorbar=None)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn [8], line 3[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcollections[39;00m [38;5;28;01mimport[39;00m Counter
[0;32m----> 3[0m [38;5;28;01mimport[39;00m [38;5;21;01mseaborn[39;00m [38;5;28;01mas[39;00m [38;5;21;01msns[39;00m
[1;32m      5[0m counter [38;5;241m=[39m Counter(df_y[38;5;241m.[39mvalues)
[1;32m      6[0m sns[38;5;241m.[39mbarplot(y[38;5;241m=[39m[38;5;28mlist[39m(counter[38;5;241m.[39mvalues()), x[38;5;241m=[39m[38;5;28mlist[39m(counter[38;5;241m.[39mkeys()), errorbar[38;5;241m=[39m[38;5;28;01mNone[39;00m)

[0;31mModuleNotFoundError[0m: No module named 'seaborn'
ModuleNotFoundError: No module named 'seaborn'

